---
dependencies:
  - { role: docker/destroy-container, when: reinstall }
  - { role: docker/docker-image }
  - { role: products/hand_h/docker-container }
  - { role: products/hand_h/desktop-icons }
  - { role: products/common/optoforce, when: optoforce }
  - { role: aws, when: aws }
  - { role: save-logs }