---
- name: Creating the container
  tasks:
    - shell: id -u
      register: id
    
  docker_container:
    name: {{ name }}
    image: {{ image }}
    env:
        verbose: "true"
        interface: {{ ethercatinterface }}
        QT_X11_NO_MITSHM: 1
        LOCAL_USER_ID: id.stdout
    network_mode: "host"
    privileged: yes
    interactive: yes
    volumes: "/tmp/.X11-unix:/tmp/.X11-unix"[rw]
    command: "terminator -x bash -c 'pkill -f \'^\'shadow_launcher_app_xterm && /usr/local/bin/setup_modular_grasper.sh && bash || bash"
