---
- name: Teleop deploy playbook for teleop server
  import_playbook: ../../../teleop_deploy.yml
    image="shadowrobot/dexterous-hand"
    tag="kinetic-release"
    reinstall=true
    use_openvpn=false
    ethercat_interface="enp0s25"
    nvidia_docker=false
    skip_molecule_task=true
    allow_auto_reboot=true
    glove=cyberglove
