---
image: "shadowrobot/shadow-teleop"
tag: "kinetic-release"
reinstall: false
container_name: "teleop"
nvidia_docker: 2
glove: "cyberglove"
cyberglove: "A-penny"
use_aws: false
use_openvpn: false
setup_directory: "/usr/local/bin"
ethercat_interface: "eth0"
config_branch: "demohand_A"
allow_auto_reboot: true
user: "{{ ansible_user_id }}"
user_folder: "/home/{{ user }}"
shadow_hand_launcher_folder: "{{ user_folder }}/.shadow_launcher_app/shadow_hand_launcher"
launch_hand: false
use_steamvr: false
use_cyberglove: false
remote_cyberglove: true
setup_script: ""
server_hostname: "TELEOP-DEMO"
openvpn_port: "1196"
terminator: true
