---
image: "shadowrobot/shadow-teleop"
tag: "kinetic-release"
reinstall: false
container_name: "teleop"
nvidia_docker: false
cyberglove: "A-penny"
use_aws: false
use_openvpn: false
setup_script: "/usr/local/bin/teleop-client-setup.sh"
