---
image: "shadowrobot/shadow-teleop" # Docker image name
tag: "kinetic-v0.0.10" # Tag of the exact Docker hub image to pull
reinstall: false # Flag to know if the docker container should be fully reinstalled
container_name: "teleop" # Name of the docker container
ethercat_interface: "eth0" # Ethercat interface of the hand
config_branch: "demohand_A" # Specify the branch for the specific hand (Only for dexterous hand)
allow_auto_reboot: true # Allow Ansible to reboot the control-machine automatically during software installation
use_aws: false # Boolean to indicate whether ROS logs will be uploaded to AWS S3
cyberglove: "A-penny" # Specify the branch of sr_cyberglove_config for cyberglove configuration
setup_directory: "/usr/local/bin" # Where setup scripts should be installed that are launched when Docker starts
terminator: false # Launch terminator when the Docker starts
