---
- name: Teleop deploy playbook for teleop server
  import_playbook: ../../teleop-deploy.yml
    reinstall=true
    use_openvpn=false
    ethercat_interface="enp0s25"
    image="10.6.10.7:5000/dexterous-hand"
    tag="kinetic-release"
