---
- name: Create the shadow_hand_launcher_folder
  become: yes
  file:
    path: "{{ shadow_hand_launcher_folder }}"
    state: directory

- name: Creating hand setup script
  become: yes
  template:
    src: templates/scripts/setup-hand.j2
    dest: "{{ shadow_hand_launcher_folder }}/setup_dexterous_hand.sh"
    mode: '755'

- name: Creating the container
  become: yes
  docker_container:
    name: "{{ container_name }}"
    image: "{{ full_image_name }}"
    state: present
    recreate: yes
    pull: yes
    env:
      verbose: "true"
      interface: "{{ ethercat_interface }}"
      QT_X11_NO_MITSHM: "1"
      LOCAL_USER_ID: "{{ id.stdout }}"
      DISPLAY: :0
    network_mode: "host"
    privileged: yes
    interactive: yes
    volumes: /tmp/.X11-unix:/tmp/.X11-unix[rw]
    command: "terminator -x bash -c '/usr/local/bin/setup_dexterous_hand.sh && bash || bash'"

- name: Copying hand setup script into docker container
  become: yes
  shell: "docker cp {{ shadow_hand_launcher_folder }}/setup_dexterous_hand.sh {{ container_name }}:/usr/local/bin/setup_dexterous_hand.sh"
