---
openvpn_apt_repository: 'deb [arch=amd64] http://build.openvpn.net/debian/openvpn/release/2.4/ {{ ansible_distribution_release }} stable'
user: "{{ ansible_user_id }}"
user_folder: "/home/{{ user }}"
client_name: "teleop-client"