---
dependencies:
  - { role: docker/destroy-container, when: reinstall }
  - { role: docker/docker-image }
  - { role: products/hand_e/docker-container }
  - { role: products/hand_e/desktop-icons }
  - { role: products/common/cyberglove, when: use_cyberglove }
  - { role: products/common/optoforce, when: use_optoforce }
  - { role: aws, when: customerkey }