---
# mongodb installation (noetic)

- name: Update package lists
  apt:
    update_cache: yes
  become: yes

- name: Installing mongodb packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - mongodb-server-core
      - ros-noetic-warehouse-ros
      - ros-noetic-warehouse-ros-mongo
  become: yes

