---
dependencies:
  - { role: installation/docker }
  - { role: installation/nvidia-docker, when: nvidia_docker|bool }
  - { role: docker/docker-image }
  - { role: products/hand-e/docker-container }
  - { role: products/hand-e/desktop-icons }
  - { role: products/teleop/server/desktop-icons }
  - { role: products/hand-e/cyberglove, when: use_cyberglove|bool }
  - { role: docker/aws, when: use_aws|bool }