---
- name: Add IP address of all hosts to server (running Ansible)
  hosts: server
  tasks:
    lineinfile:
      dest: /etc/hosts
      regexp: '^{{ item }}.*$'
      line: "{{ item }} {{ hostvars[item].ansible_host }}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"
    become: yes

- name: Install Python 3
  import_playbook: ./install-python3.yml

- name: Check which hosts are available for teleop system Install
  hosts: all
  gather_facts: false
  tasks:
    - name: ping all the machines
      ping:

- name: Install Teleop software on Ubuntu teleop server laptop
  hosts: server
  pre_tasks:
    - name: check if cyberglove branch is provided
      when: cyberglove is defined and cyberglove|bool
      set_fact:
        use_cyberglove: true

  roles:
    - { role: products/teleop/server/deploy }

- name: Install Teleop software on control machine
  hosts: control-machine
  pre_tasks:
    - name: check if cyberglove branch is provided
      when: cyberglove is defined and cyberglove|bool
      set_fact:
        use_cyberglove: true

    - name: Add IP address of all hosts to all hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^{{ item }}.*$'
        line: "{{ item }} {{ hostvars[item].ansible_host }}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"
      become: yes

  roles:
    - { role: products/teleop/control-machine/deploy }

- name: Install Teleop software on Windows Machine
  hosts: windows-machine
  pre_tasks:
    - name: Add IP address of all hosts to all hosts
      lineinfile:
        dest: c:\Windows\System32\Drivers\etc\hosts
        regexp: '^{{ item }}.*$'
        line: "{{ item }} {{ hostvars[item].ansible_host }}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"
      become: yes

  roles:
    - { role: products/teleop/windows-machine/deploy }

- name: Install Teleop software on Ubuntu teleop client laptop
  hosts: client
  pre_tasks:
    - name: check if cyberglove branch is provided
      when: cyberglove is defined and cyberglove|bool
      set_fact:
        use_cyberglove: true

    - name: Add IP address of all hosts to all hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^{{ item }}.*$'
        line: "{{ item }} {{ hostvars[item].ansible_host }}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"
      become: yes

  roles:
    - { role: products/teleop/client/deploy }
