version: '3'

services:
  sut:
    build: .
    command: >
      bash -c "pip3 list | grep molecule &&
               pip3 list | grep ansible &&
               pip3 list | grep docker"
    environment:
      - SOURCE_BRANCH
