---
user_folder: "/home/{{ user }}"
shadow_hand_launcher_folder: "{{ user_folder }}/.shadow_launcher_app/shadow_hand_launcher"
container_name: "dexterous_hand_real_hw"
use_cyberglove: false
desktop_path: "{{ user_folder }}/Desktop"
