---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: "default_ec2_{{ 9999 | random }}"
    image: ami-04606ba5d5fb731cc
    instance_type: t2.micro
    region: eu-west-2
    vpc_id: vpc-0f8cc2cc245d57eb4
    vpc_subnet_id: subnet-09c91c82c471613fc
    groups:
      - docker-deploy
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../roles
  connection_options:
    ansible_python_interpreter: /usr/bin/python3
  inventory:
    links:
      group_vars: ../../../inventory/local/group_vars
  playbooks:
    create: ../resources/ec2/create.yml
    destroy: ../resources/ec2/destroy.yml
    prepare: ../../install-python3.yml
    converge: ../default/playbook.yml
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  directory: ../default/tests/
  lint:
    name: flake8
