---
- name: Update package lists
  apt:
    update_cache: yes
  become: yes

- name: Intall needed libs for AWS CLI help
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - less
      - groff
  become: yes

- name: Make sure AWS requirements.txt exists locally
  copy:
    src: files/requirements.txt
    dest: "/tmp/aws-cli-requirements.txt"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

- name: Install AWS CLI
  pip:
    requirements: "/tmp/aws-cli-requirements.txt"
  become: true

- name: Removing aws-cli-requirements.txt local
  file:
    path: "/tmp/shadow-upload.sh"
    state: absent
