---
user: "{{ ansible_user_id }}"
user_folder: "/home/{{ user }}"
shadow_hand_launcher_folder: "{{ user_folder }}/.shadow_launcher_app/"
desktop_path: "{{ user_folder }}/Desktop"
shadow_demos_folder: "{{ desktop_path }}/Shadow Demos/"
shadow_advanched_launchers_folder: "{{ desktop_path }}/Shadow Advanced Launchers/"
