---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: default_docker
    image: shadowrobot/aurora-test-ubuntu-docker:xenial-manual
    groups:
      - docker-deploy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../roles
  inventory:
    links:
      group_vars: ../../../inventory/local/group_vars
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
