---
user_folder: "/home/{{ lookup('env','USER') }}"
shadow_hand_launcher_folder: "{{ user_folder }}/.shadow_launcher_app/shadow_hand_launcher"
save_latest_ros_logs_folder: "{{ user_folder }}/.shadow_save_log_app/save_latest_ros_logs"
container_name : "shadow_dexterous_hand"