---
- name: Ensures that Desktop folder exists
  file:
    path: "{{ user_folder }}/Desktop"
    mode: '755'
    state: directory

- name: Ensures that shadow_hand_launcher directory exists
  file:
    path: "{{ shadow_hand_launcher_folder }}"
    state: directory

- name: Copy Teleop desktop icon
  copy: 
    src: files/cyberglove_teleop.png
    dest: "{{ shadow_hand_launcher_folder }}/cyberglove_teleop.png"
    mode: '664'

- name: Create Teleop executable launch script
  template:
    src: ../../../common/resources/templates/scripts/start-docker-container.j2
    dest: "{{ shadow_hand_launcher_folder }}/teleop_exec.sh"
    mode: '755'

- name: Create Teleop desktop icon
  template:
    src: ../../../common/resources/templates/desktop-icons/standard-icon.j2
    dest: "{{ user_folder }}/Desktop/Teleop_Container_Launch.desktop"
    mode: '755'
  vars:
    desktop_shortcut_name: Teleop_Container_Launcher
    comment: "This is application launches the Teleop Container"
    folder: "{{ shadow_hand_launcher_folder }}"
    shell_script_file_name: teleop_exec.sh
    icon_file_name: cyberglove_teleop.png
    start_terminal: "true"

- name: Make Desktop icon trusted
  shell: gio set "{{ user_folder }}/Desktop/Teleop_Container_Launch.desktop" "metadata::trusted" yes
  when:
    - ansible_distribution|string == 'Ubuntu'
    - ansible_distribution_release|string == 'bionic'

- name: Copy Cyberglove desktop icon
  copy:
    src: files/cyberglove.jpg
    dest: "{{ shadow_hand_launcher_folder }}/cyberglove.jpg"
    mode: '664'

- name: Create executable launch script for Cyberglove
  template:
    src: ../../../common/resources/templates/scripts/roslaunch-script.j2
    dest: "{{ shadow_hand_launcher_folder }}/roslaunch-cyberglove.sh"
    mode: '755'
  vars:
    project_name: sr_teleop_vive_cyberglove
    launch_file: 'remote_equipment.launch cyberglove:=true'

- name: Create desktop icon for Cyberglove
  template:
    src: ../../../common/resources/templates/desktop-icons/standard-icon.j2
    dest: "{{ user_folder }}/Desktop/Cyberglove_Launch.desktop"
    mode: '755'
  vars:
    desktop_shortcut_name: "Cyberglove_Launch"
    comment: "Cyberglove_Launch"
    folder: "{{ shadow_hand_launcher_folder }}"
    shell_script_file_name: "roslaunch-cyberglove.sh"
    icon_file_name: "cyberglove.jpg"
    start_terminal: "true"

- name: Make desktop icon for Cyberglove icon trusted
  shell: gio set "{{ user_folder }}/Desktop/Cyberglove_Launch.desktop" "metadata::trusted" yes
  when:
    - ansible_distribution|string == 'Ubuntu'
    - ansible_distribution_release|string == 'bionic'
