---
image: "shadowrobot/dexterous-hand"
tag: "kinetic-release"
reinstall: false
container_name: "control-machine"
ethercat_interface: "eth0"
config_branch: "demohand_A"
allow_auto_reboot : true
user: "{{ ansible_user_id }}"
user_folder: "/home/{{ user }}"